{
  pkgs,
  config,
  lib,
  ...
}:
let
  pywalfoxNativeMessagingHost = pkgs.writeTextDir "lib/mozilla/native-messaging-hosts/pywalfox.json" (
    builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.pywalfox-native}/bin/pywalfox";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    }
  );
in
{
  programs.firefox = {
    enable = true;
    configPath = "${config.xdg.configHome}/mozilla/firefox";
    nativeMessagingHosts = [ pywalfoxNativeMessagingHost ];

    profiles = {
      lysec = {
        isDefault = true;

        extensions.packages = with pkgs.nur.repos.rycee.firefox-addons; [
          bitwarden
          darkreader
          sponsorblock
          ublock-origin
          pywalfox
        ];

        settings = {
          "browser.startup.page" = 3;

          # Remember zoom level per site
          "browser.zoom.siteSpecific" = true;

          # Cookie persistence behavior
          "network.cookie.lifetimePolicy" = 0; # Accept cookies normally
          "privacy.clearOnShutdown.cookies" = false; # Don't clear cookies on shutdown
          "privacy.clearOnShutdown.siteSettings" = false; # Keep site permissions/settings
          "privacy.sanitize.sanitizeOnShutdown" = false; # Disable general auto-cleanup

          # Needed for proper zoom and feature behavior — disables anti-fingerprinting zoom locking
          "privacy.resistFingerprinting" = false;

          # URL bar autocomplete behavior
          "browser.urlbar.autoFill" = true; # Autocomplete URLs as you type
          "browser.urlbar.dnsFirstForSingleWords" = true; # Resolve single words as domains if possible

          # Enable suggestions in the address bar
          "browser.urlbar.suggest.history" = true; # Suggest URLs from history
          "browser.urlbar.suggest.bookmark" = true; # Suggest bookmarks
          "browser.urlbar.suggest.openpage" = true; # Suggest open tabs
          "browser.urlbar.suggest.searches" = true; # Suggest search engine suggestions

          # Enable search suggestions in the search bar
          "browser.search.suggest.enabled" = true;

          # Disable password saving prompt
          "signon.rememberSignons" = false;
          "passwordmanager.enabled" = false;

          # Middle-click autoscroll (Settings → "Use autoscrolling" maps to general.autoScroll)
          "general.autoScroll" = true;

          # Stop Linux middle-click paste / open-URL from blocking autoscroll
          "middlemouse.contentLoadURL" = false;
          "middlemouse.paste" = false;

          # userChrome.css / userContent.css
          "toolkit.legacyUserProfileCustomizations.stylesheets" = true;

          # Remove the "Firefox View" button/tab
          "browser.tabs.firefox-view" = false;

          # Native vertical tabs (Firefox 136+)
          "sidebar.revamp" = true;
          "sidebar.verticalTabs" = true;
          "sidebar.visibility" = "always-show";

          # Disable Pocket integration (saves articles to Firefox Account)
          "extensions.pocket.enabled" = false;

          # Remove ads and sponsored content from new tab page
          "browser.newtabpage.activity-stream.showSponsored" = false;
          "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;

          # Disable news/top stories from Mozilla on new tab page
          "browser.newtabpage.activity-stream.feeds.system.topstories" = false;

          # (Optional additions if you want a clean new tab page)
          # Disable highlights like recent history and bookmarks
          # "browser.newtabpage.activity-stream.feeds.section.highlights" = false;
          # "browser.newtabpage.activity-stream.section.highlights.includeVisited" = false;
          # "browser.newtabpage.activity-stream.section.highlights.includeBookmarks" = false;
        };

        userChrome = ''
          *,
          *::before,
          *::after {
            border-radius: 0 !important;
          }

          .titlebar-buttonbox-container {
            display: none !important;
          }
        '';

        # Applied to all web pages (not browser chrome).
        userContent = ''
          *,
          *::before,
          *::after {
            border-radius: 0 !important;
          }
        '';

        search = {
          force = true;
          default = "google";
          order = [
            "google"
            "searxng"
            "nix-packages"
            "nixos-wiki"
            "ddg"
          ];

          engines = {
            searxng = {
              urls = [
                { template = "https://searx.org/search?q={searchTerms}"; }
              ];
              icon = "https://searx.org/favicon.ico";
              updateInterval = 86400000; # 24h
              definedAliases = [ "@searx" ];
              suggestUrls = [
                { template = "https://searx.org/autosuggest?q={searchTerms}"; }
              ];
            };

            "nix-packages" = {
              urls = [
                {
                  template = "https://search.nixos.org/packages?type=packages&query={searchTerms}";
                  params = [
                    {
                      name = "type";
                      value = "packages";
                    }
                    {
                      name = "query";
                      value = "{searchTerms}";
                    }
                  ];
                }
              ];
              icon = "https://nixos.wiki/favicon.png";
              definedAliases = [ "@np" ];
            };

            "nixos-wiki" = {
              urls = [
                { template = "https://nixos.wiki/index.php?search={searchTerms}"; }
              ];
              icon = "https://nixos.wiki/favicon.png";
              updateInterval = 86400000;
              definedAliases = [ "@nw" ];
            };

            ddg = {
              urls = [
                { template = "https://duckduckgo.com/?q={searchTerms}"; }
              ];
              definedAliases = [ "@ddg" ];
            };

            # Hide Bing from the UI
            bing.metaData.hidden = true;

            # Give Google an alias
            google.metaData.alias = "@g";
          };
        };
      };
    };
  };

  home.activation.migrateFirefoxProfile = lib.hm.dag.entryBefore [ "writeBoundary" ] ''
    legacy="$HOME/.mozilla/firefox"
    target="${config.programs.firefox.configPath}"
    if [ -d "$legacy" ] && [ ! -e "$target" ]; then
      $DRY_RUN_CMD mkdir -p "$(dirname "$target")"
      $DRY_RUN_CMD mv "$legacy" "$target"
    fi
  '';
}
